stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE_NAME: "olooeez/$CI_PROJECT_NAME"
  DOCKER_IMAGE_TAG: "$CI_COMMIT_TAG"

before_script:
  - sudo apt-get update -qy
  - sudo apt-get install libcriterion-dev -y

build:
  stage: build
  script:
    - make
  tags:
    - gcc

test:
  stage: test
  script:
    - make
    - make check
    - make coverage
  coverage: /^\s*lines:\s*\d+.\d+\%/
  tags:
    - gcc

deploy:
  stage: deploy
  only:
    - tags
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" .
    - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
    - docker tag "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" "$DOCKER_IMAGE_NAME:latest"
    - docker push "$DOCKER_IMAGE_NAME:latest"
  tags:
    - docker
